steps:
    build:
        image: codeberg.org/generic-pers0n/tenacity-alpine:latest
        commands:
            - mkdir build
            - cmake -DMIDI=Off -S . -B build
            - cmake --build ./build -j $(nproc)
        when:
            branch: main
            event: [pull_request, push]
